-- 实体类型 → 菜单映射（覆盖全部 74 个业务实体）
insert into rbac_entity_menu_map (entity_type, menu_key) values
  ('products', 'products-products'),
  ('product_categories', 'products-dictionary'),
  ('fabric_types', 'products-dictionary'),
  ('filling_types', 'products-dictionary'),
  ('customers', 'marketing-customers'),
  ('sales_orders', 'marketing-orders'),
  ('shipments', 'marketing-shipments'),
  ('sales_outbounds', 'marketing-shipments'),
  ('follow_ups', 'marketing-customers'),
  ('price_lists', 'marketing-price'),
  ('customer_discounts', 'marketing-customers'),
  ('exchange_rates', 'marketing-price'),
  ('quotes', 'quotation-list'),
  ('contracts', 'contract-list'),
  ('contract_templates', 'contract-templates'),
  ('production_plans', 'planning-mps'),
  ('work_orders', 'production-orders'),
  ('work_order_costs', 'production-costs'),
  ('production_lines', 'planning-production-line'),
  ('production_line_equipments', 'planning-production-line'),
  ('production_exceptions', 'production-orders'),
  ('processes', 'process-processes'),
  ('process_routes', 'process-routes'),
  ('process_param_templates', 'process-params'),
  ('process_versions', 'process-versions'),
  ('process_knowledge', 'process-knowledge'),
  ('quality_standards', 'quality-standards'),
  ('process_inspection_standards', 'quality-standards'),
  ('quality_inspections', 'quality-finished'),
  ('material_inspections', 'quality-incoming'),
  ('process_inspections', 'quality-process'),
  ('finished_inspections', 'quality-finished'),
  ('equipment', 'equipment-ledger'),
  ('maintenance_plans', 'equipment-plan'),
  ('equipment_records', 'equipment-maintain'),
  ('safety_records', 'safety-hazard'),
  ('materials', 'materials'),
  ('inventory', 'inventory-material'),
  ('warehouse_locations', 'inventory-location'),
  ('stock_records', 'inventory-records'),
  ('finished_goods_inbounds', 'inventory-finished_inbound'),
  ('suppliers', 'purchase-supplier'),
  ('purchase_requests', 'purchase-po'),
  ('purchase_orders', 'purchase-po'),
  ('purchase_arrivals', 'purchase-arrival'),
  ('purchase_returns', 'purchase-arrival'),
  ('material_requisitions', 'production-requisitions'),
  ('payment_records', 'finance-payment'),
  ('finance_records', 'finance-cost'),
  ('employees', 'personnel-employee'),
  ('system_users', 'system-users'),
  ('attendance_records', 'personnel-attendance'),
  ('leave_records', 'personnel-leave'),
  ('performance_records', 'personnel-performance'),
  ('performance_grade_config', 'personnel-performance'),
  ('training_records', 'personnel-training'),
  ('evaluation_items', 'personnel-performance'),
  ('inventory_turnovers', 'inventory-turnover'),
  ('safety_patrol_plans', 'safety-patrol'),
  ('safety_patrol_tasks', 'safety-patrol-tasks'),
  ('alert_notifications', 'system-basic'),
  ('after_sales_tickets', 'after-sales-tickets'),
  ('after_sales_returns', 'after-sales-returns'),
  ('after_sales_reshipments', 'after-sales-reshipments'),
  ('material_supplier_prices', 'materials'),
  ('ecommerce_purchase_tracking', 'marketing-orders'),
  ('outsourcing_dispatches', 'outsourcing-shipment'),
  ('outsourcing_return_qcs', 'outsourcing-return'),
  ('outsource_processing_payments', 'outsourcing-factory'),
  ('outsource_factories', 'outsourcing-factory'),
  ('outsource_shipments', 'outsourcing-shipment'),
  ('outsource_returns', 'outsourcing-return');

-- 角色基础信息
insert into sys_roles (role_key, role_name, data_scopes) values
  ('admin', '管理员', '{"_default":"all"}'::jsonb),
  ('production', '生产主管', '{"_default":"dept"}'::jsonb),
  ('worker', '生产人员', '{"_default":"self"}'::jsonb),
  ('quality', '质检员', '{"_default":"dept"}'::jsonb),
  ('warehouse', '仓库管理员', '{"_default":"all"}'::jsonb),
  ('finance', '财务人员', '{"_default":"all"}'::jsonb),
  ('sales', '销售', '{"_default":"self"}'::jsonb);